# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------



TEMPLATE = lib
TARGET = QMeshLib
CONFIG += staticlib debug
QT += opengl
QT += widgets
DEFINES += _WINDOWS _UNICODE _ENABLE_EXTENDED_ALIGNED_STORAGE WIN64 _WINDOWS _UNICODE _ENABLE_EXTENDED_ALIGNED_STORAGE WIN64
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
HEADERS += $$PWD/../ThirdPartyDependence/PQPLib/BV.h \
    $$PWD/../ThirdPartyDependence/PQPLib/BVTQ.h \
    $$PWD/../ThirdPartyDependence/PQPLib/Build.h \
    $$PWD/../ThirdPartyDependence/PQPLib/GetTime.h \
    $$PWD/../ThirdPartyDependence/PQPLib/MatVec.h \
    $$PWD/../ThirdPartyDependence/PQPLib/OBB_Disjoint.h \
    $$PWD/../ThirdPartyDependence/PQPLib/PQP.h \
    $$PWD/../ThirdPartyDependence/PQPLib/PQP_Compile.h \
    $$PWD/../ThirdPartyDependence/PQPLib/PQP_Internal.h \
    PolygenMesh.h \
    QMeshCluster.h \
    QMeshEdge.h \
    QMeshFace.h \
    QMeshNode.h \
    QMeshPatch.h \
    QMeshTetra.h \
    $$PWD/../ThirdPartyDependence/PQPLib/RectDist.h \
    $$PWD/../ThirdPartyDependence/PQPLib/Tri.h \
    $$PWD/../ThirdPartyDependence/PQPLib/TriDist.h \
    $$PWD/../ThirdPartyDependence/QHullLib/geom.h \
    $$PWD/../ThirdPartyDependence/QHullLib/io.h \
    $$PWD/../ThirdPartyDependence/QHullLib/mem.h \
    $$PWD/../ThirdPartyDependence/QHullLib/merge.h \
    $$PWD/../ThirdPartyDependence/QHullLib/poly.h \
    $$PWD/../ThirdPartyDependence/QHullLib/qhull.h \
    $$PWD/../ThirdPartyDependence/QHullLib/qhull_a.h \
    $$PWD/../ThirdPartyDependence/QHullLib/qset.h \
    $$PWD/../ThirdPartyDependence/QHullLib/stat.h \
    $$PWD/../ThirdPartyDependence/QHullLib/user.h \

SOURCES += $$PWD/../ThirdPartyDependence/PQPLib/BV.cpp \
    $$PWD/../ThirdPartyDependence/PQPLib/Build.cpp \
    $$PWD/../ThirdPartyDependence/PQPLib/PQP.cpp \
	$$PWD/../ThirdPartyDependence/PQPLib/TriDist.cpp \
    PolygenMesh.cpp \
    QMeshCluster.cpp \
    QMeshEdge.cpp \
    QMeshFace.cpp \
    QMeshNode.cpp \
    QMeshPatch.cpp \
    QMeshTetra.cpp \
    $$PWD/../ThirdPartyDependence/QHullLib/geom.cpp \
    $$PWD/../ThirdPartyDependence/QHullLib/geom2.cpp \
    $$PWD/../ThirdPartyDependence/QHullLib/global.cpp \
    $$PWD/../ThirdPartyDependence/QHullLib/io.cpp \
    $$PWD/../ThirdPartyDependence/QHullLib/men.cpp \
    $$PWD/../ThirdPartyDependence/QHullLib/merge.cpp \
    $$PWD/../ThirdPartyDependence/QHullLib/poly.cpp \
    $$PWD/../ThirdPartyDependence/QHullLib/poly2.cpp \
    $$PWD/../ThirdPartyDependence/QHullLib/qconvex.cpp \
    $$PWD/../ThirdPartyDependence/QHullLib/qhull.cpp \
    $$PWD/../ThirdPartyDependence/QHullLib/qset.cpp \
    $$PWD/../ThirdPartyDependence/QHullLib/rbox.cpp \
    $$PWD/../ThirdPartyDependence/QHullLib/stat.cpp \
    $$PWD/../ThirdPartyDependence/QHullLib/user.cpp \
    
INCLUDEPATH += $$PWD/../ThirdPartyDependence/glut


win32:CONFIG(release, debug|release): LIBS += -L$$OUT_PWD/../ThirdPartyDependence/glu -lglut32
else:win32:CONFIG(debug, debug|release): LIBS += -L$$OUT_PWD/../ThirdPartyDependence/glu -lglut32

win32:CONFIG(release, debug|release): LIBS += -L$$OUT_PWD/../ThirdPartyDependence/glu -lOpenGL32
else:win32:CONFIG(debug, debug|release): LIBS += -L$$OUT_PWD/../ThirdPartyDependence/glu -lOpenGL32

win32:CONFIG(release, debug|release): LIBS += -L$$OUT_PWD/../ThirdPartyDependence/glu -lGlU32
else:win32:CONFIG(debug, debug|release): LIBS += -L$$OUT_PWD/../ThirdPartyDependence/glu -lGlU32
